name: Nest.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: '代码迁出到服务器'
        uses: actions/checkout@v3

      - name: 调用 Node.js, 版本-- ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: 安装项目依赖
        run: npm i

      - name: 打包项目
        run: npm run build

      - name: 重启PM2
        run: pm2 stop 0 |
          pm2 start 0
          pm2 save
      
      - name: 重启Nginx
        run: sudo service nginx restart

